// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantMenu.Feedback.Infrastructure.Database;

#nullable disable

namespace RestaurantMenu.Feedback.Infrastructure.Database.Migrations
{
    [DbContext(typeof(FeedbackDbContext))]
    partial class FeedbackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("feedback")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantMenu.Feedback.Domain.FeedbackEntries.FeedbackEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DiningSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("dining_session_id");

                    b.Property<DateTimeOffset?>("HiddenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_at_utc");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("OrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_line_id");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sentiment");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DiningSessionId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_feedback_session_order")
                        .HasFilter("order_line_id is null");

                    b.HasIndex("RestaurantId", "CreatedAtUtc")
                        .HasDatabaseName("ix_feedback_restaurant_created");

                    b.HasIndex("DiningSessionId", "OrderId", "OrderLineId")
                        .IsUnique()
                        .HasDatabaseName("ux_feedback_session_order_line")
                        .HasFilter("order_line_id is not null");

                    b.HasIndex("RestaurantId", "BranchId", "CreatedAtUtc")
                        .HasDatabaseName("ix_feedback_branch_created");

                    b.ToTable("feedback_entries", "feedback", t =>
                        {
                            t.HasCheckConstraint("ck_feedback_rating", "rating between 1 and 5");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
