using System.Net;
using System.Net.Http.Json;
using System.Text.Json;

using RestaurantMenu.Api.FunctionalTests.Infrastructure;
using RestaurantMenu.Restaurants.Domain.Memberships;
namespace RestaurantMenu.Api.FunctionalTests.Restaurants;

public sealed class MembershipLifecycleTests(TestWebApplicationFactory factory) : IClassFixture<TestWebApplicationFactory>
{
    [Fact]
    public async Task InvitationAcceptanceIsSingleUseAndLifecycleIsTenantScoped()
    { await factory.MigrateDatabaseAsync(); var restaurant = await factory.SeedRestaurantAsync($"Members {Guid.NewGuid():N}", DateTimeOffset.UtcNow); var rid = restaurant.Id.Value; using var client = factory.CreateClient(); using var invite = await client.PostAsJsonAsync($"/api/restaurants/{rid}/member-invitations", new { Email = "New.User@example.com", Role = RestaurantMembershipRole.Staff }); invite.EnsureSuccessStatusCode(); var issued = await invite.Content.ReadFromJsonAsync<JsonElement>(); var token = issued.GetProperty("token").GetString(); using var duplicate = await client.PostAsJsonAsync($"/api/restaurants/{rid}/member-invitations", new { Email = "new.user@example.com", Role = RestaurantMembershipRole.Staff }); Assert.Equal(HttpStatusCode.Conflict, duplicate.StatusCode); using var accept = await client.PostAsJsonAsync("/api/public/member-invitations/accept", new { Token = token }); accept.EnsureSuccessStatusCode(); using var replay = await client.PostAsJsonAsync("/api/public/member-invitations/accept", new { Token = token }); Assert.Equal(HttpStatusCode.Conflict, replay.StatusCode); var subject = "subject:new.user@example.com"; using (var escalate = new HttpRequestMessage(HttpMethod.Post, $"/api/restaurants/{rid}/member-invitations") { Content = JsonContent.Create(new { Email = "owner@example.com", Role = RestaurantMembershipRole.Owner }) }) { escalate.Headers.Add(TestAuthenticationHandler.SubjectHeader, subject); escalate.Headers.Add(TestAuthenticationHandler.PermissionsHeader, "members.write"); Assert.Equal(HttpStatusCode.Conflict, (await client.SendAsync(escalate)).StatusCode); } using var members = await client.GetAsync($"/api/restaurants/{rid}/members"); members.EnsureSuccessStatusCode(); var list = await members.Content.ReadFromJsonAsync<JsonElement>(); Assert.Equal(2, list.GetArrayLength()); using var revokeMember = await client.PutAsJsonAsync($"/api/restaurants/{rid}/members/{subject}", new { Role = RestaurantMembershipRole.Staff, Status = RestaurantMembershipStatus.Revoked, ExpectedVersion = 1 }); revokeMember.EnsureSuccessStatusCode(); using (var denied = new HttpRequestMessage(HttpMethod.Get, $"/api/restaurants/{rid}/members")) { denied.Headers.Add(TestAuthenticationHandler.SubjectHeader, subject); denied.Headers.Add(TestAuthenticationHandler.PermissionsHeader, "members.read"); Assert.Equal(HttpStatusCode.Forbidden, (await client.SendAsync(denied)).StatusCode); } using var audit = await client.GetAsync($"/api/restaurants/{rid}/membership-audit"); audit.EnsureSuccessStatusCode(); Assert.Equal(3, (await audit.Content.ReadFromJsonAsync<JsonElement>()).GetArrayLength()); using var cross = await client.GetAsync($"/api/restaurants/{Guid.NewGuid()}/members"); Assert.Equal(HttpStatusCode.Forbidden, cross.StatusCode); }
    [Fact] public async Task FinalOwnerCannotBeSuspended() { await factory.MigrateDatabaseAsync(); var restaurant = await factory.SeedRestaurantAsync($"Owner {Guid.NewGuid():N}", DateTimeOffset.UtcNow); using var client = factory.CreateClient(); using var response = await client.PutAsJsonAsync($"/api/restaurants/{restaurant.Id.Value}/members/{TestAuthenticationHandler.DefaultSubject}", new { Role = RestaurantMembershipRole.Owner, Status = RestaurantMembershipStatus.Suspended, ExpectedVersion = 1 }); Assert.Equal(HttpStatusCode.Conflict, response.StatusCode); }
    [Fact] public async Task RevokedInvitationCannotBeAcceptedAndIsVisibleWithoutToken() { await factory.MigrateDatabaseAsync(); var restaurant = await factory.SeedRestaurantAsync($"Revoke {Guid.NewGuid():N}", DateTimeOffset.UtcNow); using var client = factory.CreateClient(); using var invite = await client.PostAsJsonAsync($"/api/restaurants/{restaurant.Id.Value}/member-invitations", new { Email = "revoked@example.com", Role = RestaurantMembershipRole.Staff }); invite.EnsureSuccessStatusCode(); var value = await invite.Content.ReadFromJsonAsync<JsonElement>(); var id = value.GetProperty("id").GetGuid(); var token = value.GetProperty("token").GetString(); using var revoke = await client.PostAsJsonAsync($"/api/restaurants/{restaurant.Id.Value}/member-invitations/{id}/revoke", new { ExpectedVersion = 1 }); revoke.EnsureSuccessStatusCode(); using var accept = await client.PostAsJsonAsync("/api/public/member-invitations/accept", new { Token = token }); Assert.Equal(HttpStatusCode.Conflict, accept.StatusCode); using var list = await client.GetAsync($"/api/restaurants/{restaurant.Id.Value}/member-invitations"); list.EnsureSuccessStatusCode(); var item = (await list.Content.ReadFromJsonAsync<JsonElement>())[0]; Assert.Equal("Revoked", item.GetProperty("status").GetString()); Assert.False(item.TryGetProperty("token", out var exposed) && exposed.ValueKind == JsonValueKind.String); }
}