using System.Globalization;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using RestaurantMenu.Payments.Application.Abstractions;
namespace RestaurantMenu.Payments.Infrastructure.Stripe;
public sealed class StripePaymentProvider(HttpClient client,StripeOptions options):IPaymentProvider
{
 public async Task<ProviderAccount>CreateConnectedAccountAsync(string country,string currency,string idempotencyKey,CancellationToken cancellationToken){using var doc=await Send(HttpMethod.Post,"v1/accounts",[("type","express"),("country",country),("default_currency",currency.ToLowerInvariant())],null,idempotencyKey,cancellationToken);return new(doc.RootElement.GetProperty("id").GetString()!);}
 public async Task<ProviderOnboardingLink>CreateOnboardingLinkAsync(string accountId,Uri refreshUrl,Uri returnUrl,CancellationToken cancellationToken){using var doc=await Send(HttpMethod.Post,"v1/account_links",[("account",accountId),("refresh_url",refreshUrl.ToString()),("return_url",returnUrl.ToString()),("type","account_onboarding")],null,null,cancellationToken);return new(new Uri(doc.RootElement.GetProperty("url").GetString()!));}
 public async Task<bool>IsAccountReadyAsync(string accountId,CancellationToken cancellationToken){using var doc=await Send(HttpMethod.Get,"v1/accounts/"+Uri.EscapeDataString(accountId),null,null,null,cancellationToken);var r=doc.RootElement;return r.GetProperty("charges_enabled").GetBoolean()&&r.GetProperty("payouts_enabled").GetBoolean()&&r.GetProperty("details_submitted").GetBoolean();}
 public async Task<ProviderPaymentIntent>CreatePaymentIntentAsync(string accountId,long amountMinor,string currency,long applicationFeeMinor,string idempotencyKey,CancellationToken cancellationToken){using var doc=await Send(HttpMethod.Post,"v1/payment_intents",[("amount",amountMinor.ToString(CultureInfo.InvariantCulture)),("currency",currency.ToLowerInvariant()),("application_fee_amount",applicationFeeMinor.ToString(CultureInfo.InvariantCulture)),("automatic_payment_methods[enabled]","true")],accountId,idempotencyKey,cancellationToken);var r=doc.RootElement;return new(r.GetProperty("id").GetString()!,r.GetProperty("client_secret").GetString()!);}
 public async Task<ProviderRefund>CreateRefundAsync(string accountId,string paymentIntentId,long amountMinor,string idempotencyKey,CancellationToken cancellationToken){using var doc=await Send(HttpMethod.Post,"v1/refunds",[("payment_intent",paymentIntentId),("amount",amountMinor.ToString(CultureInfo.InvariantCulture)),("refund_application_fee","true")],accountId,idempotencyKey,cancellationToken);return new(doc.RootElement.GetProperty("id").GetString()!);}
 public VerifiedPaymentEvent VerifyWebhook(string payload,string signatureHeader,DateTimeOffset now){var parts=signatureHeader.Split(',').Select(x=>x.Split('=',2)).Where(x=>x.Length==2).ToArray();var timestamp=parts.FirstOrDefault(x=>x[0]=="t")?[1];var signatures=parts.Where(x=>x[0]=="v1").Select(x=>x[1]).ToArray();if(!long.TryParse(timestamp,out var seconds)||Math.Abs(now.ToUnixTimeSeconds()-seconds)>300)throw new CryptographicException("Invalid timestamp.");var expected=Convert.ToHexStringLower(HMACSHA256.HashData(Encoding.UTF8.GetBytes(options.WebhookSecret),Encoding.UTF8.GetBytes(timestamp+"."+payload)));if(!signatures.Any(x=>CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(x),Encoding.ASCII.GetBytes(expected))))throw new CryptographicException("Invalid signature.");using var doc=JsonDocument.Parse(payload);var root=doc.RootElement;var obj=root.GetProperty("data").GetProperty("object");var type=root.GetProperty("type").GetString()!;var isRefund=type is "refund.created" or "refund.updated";var intent=isRefund?obj.GetProperty("payment_intent").GetString()!:obj.GetProperty("id").GetString()!;var eventId=isRefund?obj.GetProperty("id").GetString()!:root.GetProperty("id").GetString()!;long? amount=isRefund&&obj.GetProperty("status").GetString()=="succeeded"?obj.GetProperty("amount").GetInt64():null;return new(eventId!,intent!,type,amount,DateTimeOffset.FromUnixTimeSeconds(root.GetProperty("created").GetInt64()));}
 private async Task<JsonDocument>Send(HttpMethod method,string path,IEnumerable<(string,string)>?form,string? accountId,string? idempotencyKey,CancellationToken cancellationToken){using var request=new HttpRequestMessage(method,path);request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",options.SecretKey);if(accountId is not null)request.Headers.Add("Stripe-Account",accountId);if(idempotencyKey is not null)request.Headers.Add("Idempotency-Key",idempotencyKey);if(form is not null)request.Content=new FormUrlEncodedContent(form.Select(x=>new KeyValuePair<string,string>(x.Item1,x.Item2)));using var response=await client.SendAsync(request,cancellationToken);var json=await response.Content.ReadAsStringAsync(cancellationToken);response.EnsureSuccessStatusCode();return JsonDocument.Parse(json);}
}
