using RestaurantMenu.Application.Abstractions.Data;
using RestaurantMenu.Application.Abstractions.Messaging;
using RestaurantMenu.Application.Abstractions.Security;
using RestaurantMenu.Restaurants.Application.Abstractions.Data;
using RestaurantMenu.Restaurants.Application.Abstractions.Security;
using RestaurantMenu.Restaurants.Domain.Memberships;
using RestaurantMenu.Restaurants.Domain.Restaurants;
using RestaurantMenu.SharedKernel.Results;
namespace RestaurantMenu.Restaurants.Application.Memberships;

public sealed record InvitationOptions(TimeSpan Lifetime);
public sealed record InvitationResponse(Guid Id, Guid RestaurantId, string Email, string Role, string Status, DateTimeOffset ExpiresAtUtc, long Version, string? Token = null);
public sealed record MemberResponse(string Subject, string Role, string Status, long Version);
public sealed record AuditResponse(Guid Id, string ActorSubject, string Action, string ResourceType, string ResourceId, string? Changes, DateTimeOffset OccurredAtUtc);
public sealed record InviteMemberCommand(RestaurantId RestaurantId, string Email, RestaurantMembershipRole Role) : ICommand<Result<InvitationResponse>>;
public sealed class InviteMemberCommandHandler(ICurrentUser user, IRestaurantMembershipRepository members, IMembershipInvitationRepository invitations, IInvitationTokenGenerator tokens, IUnitOfWork unitOfWork, InvitationOptions options, TimeProvider clock) : ICommandHandler<InviteMemberCommand, Result<InvitationResponse>>
{ public async Task<Result<InvitationResponse>> Handle(InviteMemberCommand command, CancellationToken cancellationToken) { var actor = await members.GetAsync(command.RestaurantId, user.Subject, cancellationToken); if (actor is null || actor.Status != RestaurantMembershipStatus.Active || actor.Role != RestaurantMembershipRole.Owner && command.Role != RestaurantMembershipRole.Staff) return Result.Failure<InvitationResponse>(MembershipErrors.ForbiddenRole); var email = command.Email.Trim().ToLowerInvariant(); var now = clock.GetUtcNow(); var pending = await invitations.GetPendingByEmailAsync(command.RestaurantId, email, cancellationToken); if (pending is not null && pending.IsUsable(now)) return Result.Failure<InvitationResponse>(MembershipErrors.DuplicateInvitation); pending?.Revoke(now); var token = tokens.Generate(); var made = MembershipInvitation.Create(MembershipInvitationId.New(), command.RestaurantId, email, token.Hash, command.Role, user.Subject, now, now + options.Lifetime); if (made.IsFailure) return Result.Failure<InvitationResponse>(made.Error); invitations.Add(made.Value); Audit(invitations, command.RestaurantId, user.Subject, "InvitationCreated", made.Value.Id.Value.ToString(), now); try { await unitOfWork.SaveChangesAsync(cancellationToken); } catch (ActiveInvitationExistsException) { return Result.Failure<InvitationResponse>(MembershipErrors.DuplicateInvitation); } return Result.Success(Map(made.Value, token.Raw)); } internal static InvitationResponse Map(MembershipInvitation x, string? token = null) => new(x.Id.Value, x.RestaurantId.Value, x.Email, x.Role.ToString(), x.Status.ToString(), x.ExpiresAtUtc, x.Version, token); internal static void Audit(IMembershipInvitationRepository r, RestaurantId id, string actor, string action, string resource, DateTimeOffset now) => r.AddAudit(new(Guid.CreateVersion7(), id, actor, action, "Membership", resource, null, now)); }
public sealed record AcceptInvitationCommand(string Token) : ICommand<Result<MemberResponse>>;
public sealed class AcceptInvitationCommandHandler(IInvitationTokenGenerator tokens, IMembershipInvitationRepository invitations, IRestaurantMembershipRepository members, IIdentityProvisioner identities, IUnitOfWork unitOfWork, TimeProvider clock) : ICommandHandler<AcceptInvitationCommand, Result<MemberResponse>>
{ public async Task<Result<MemberResponse>> Handle(AcceptInvitationCommand command, CancellationToken cancellationToken) { if (!tokens.IsWellFormed(command.Token)) return Result.Failure<MemberResponse>(MembershipErrors.InvitationUnavailable); var invite = await invitations.GetByHashAsync(tokens.Hash(command.Token), cancellationToken); var now = clock.GetUtcNow(); if (invite is null || !invite.IsUsable(now)) return Result.Failure<MemberResponse>(MembershipErrors.InvitationUnavailable); var subject = await identities.EnsureUserAsync(invite.Email, cancellationToken); if (string.IsNullOrWhiteSpace(subject)) return Result.Failure<MemberResponse>(MembershipErrors.IdentityProvisioningFailed); var member = await members.GetAsync(invite.RestaurantId, subject, cancellationToken); if (member is null) { member = RestaurantMembership.Create(invite.RestaurantId, subject, invite.Role, now).Value; members.Add(member); } else member.Change(invite.Role, RestaurantMembershipStatus.Active); var accepted = invite.Accept(subject, now); if (accepted.IsFailure) return Result.Failure<MemberResponse>(accepted.Error); InviteMemberCommandHandler.Audit(invitations, invite.RestaurantId, subject, "InvitationAccepted", subject, now); try { await unitOfWork.SaveChangesAsync(cancellationToken); } catch (ConcurrencyException) { return Result.Failure<MemberResponse>(MembershipErrors.InvitationUnavailable); } return Result.Success(new MemberResponse(subject, member.Role.ToString(), member.Status.ToString(), member.Version)); } }
public sealed record ChangeMemberCommand(RestaurantId RestaurantId, string Subject, RestaurantMembershipRole Role, RestaurantMembershipStatus Status, long ExpectedVersion) : ICommand<Result<MemberResponse>>;
public sealed class ChangeMemberCommandHandler(ICurrentUser user, IRestaurantMembershipRepository members, IMembershipInvitationRepository audits, IUnitOfWork unitOfWork, TimeProvider clock) : ICommandHandler<ChangeMemberCommand, Result<MemberResponse>>
{ public async Task<Result<MemberResponse>> Handle(ChangeMemberCommand command, CancellationToken cancellationToken) { var actor = await members.GetAsync(command.RestaurantId, user.Subject, cancellationToken); var target = await members.GetAsync(command.RestaurantId, command.Subject, cancellationToken); if (actor is null || actor.Status != RestaurantMembershipStatus.Active || target is null) return Result.Failure<MemberResponse>(MembershipErrors.NotFound); if (actor.Role != RestaurantMembershipRole.Owner && (command.Role != RestaurantMembershipRole.Staff || target.Role != RestaurantMembershipRole.Staff)) return Result.Failure<MemberResponse>(MembershipErrors.ForbiddenRole); if (target.Version != command.ExpectedVersion) return Result.Failure<MemberResponse>(MembershipErrors.VersionConflict); if (target.Role == RestaurantMembershipRole.Owner && (command.Role != RestaurantMembershipRole.Owner || command.Status != RestaurantMembershipStatus.Active) && await members.CountActiveOwnersAsync(command.RestaurantId, cancellationToken) == 1) return Result.Failure<MemberResponse>(MembershipErrors.LastOwner); var result = target.Change(command.Role, command.Status); if (result.IsFailure) return Result.Failure<MemberResponse>(result.Error); InviteMemberCommandHandler.Audit(audits, command.RestaurantId, user.Subject, "MembershipChanged", target.Subject, clock.GetUtcNow()); try { await unitOfWork.SaveChangesAsync(cancellationToken); } catch (ConcurrencyException) { return Result.Failure<MemberResponse>(MembershipErrors.VersionConflict); } return Result.Success(new MemberResponse(target.Subject, target.Role.ToString(), target.Status.ToString(), target.Version)); } }
public sealed record RevokeInvitationCommand(RestaurantId RestaurantId, MembershipInvitationId Id, long ExpectedVersion) : ICommand<Result<InvitationResponse>>;
public sealed class RevokeInvitationCommandHandler(ICurrentUser user, IRestaurantMembershipRepository members, IMembershipInvitationRepository repository, IUnitOfWork unitOfWork, TimeProvider clock) : ICommandHandler<RevokeInvitationCommand, Result<InvitationResponse>>
{ public async Task<Result<InvitationResponse>> Handle(RevokeInvitationCommand command, CancellationToken cancellationToken) { var actor = await members.GetAsync(command.RestaurantId, user.Subject, cancellationToken); var value = await repository.GetAsync(command.RestaurantId, command.Id, cancellationToken); if (actor is null || actor.Status != RestaurantMembershipStatus.Active || value is null) return Result.Failure<InvitationResponse>(MembershipErrors.NotFound); if (actor.Role != RestaurantMembershipRole.Owner && value.Role != RestaurantMembershipRole.Staff) return Result.Failure<InvitationResponse>(MembershipErrors.ForbiddenRole); if (value.Version != command.ExpectedVersion) return Result.Failure<InvitationResponse>(MembershipErrors.VersionConflict); var now = clock.GetUtcNow(); value.Revoke(now); InviteMemberCommandHandler.Audit(repository, command.RestaurantId, user.Subject, "InvitationRevoked", value.Id.Value.ToString(), now); try { await unitOfWork.SaveChangesAsync(cancellationToken); } catch (ConcurrencyException) { return Result.Failure<InvitationResponse>(MembershipErrors.VersionConflict); } return Result.Success(InviteMemberCommandHandler.Map(value)); } }
public sealed record ListInvitationsQuery(RestaurantId RestaurantId) : IQuery<Result<IReadOnlyList<InvitationResponse>>>;
public sealed class ListInvitationsQueryHandler(IMembershipInvitationRepository repository) : IQueryHandler<ListInvitationsQuery, Result<IReadOnlyList<InvitationResponse>>> { public async Task<Result<IReadOnlyList<InvitationResponse>>> Handle(ListInvitationsQuery query, CancellationToken cancellationToken) => Result.Success<IReadOnlyList<InvitationResponse>>((await repository.ListAsync(query.RestaurantId, cancellationToken)).Select(x => InviteMemberCommandHandler.Map(x)).ToArray()); }
public sealed record ListMembersQuery(RestaurantId RestaurantId) : IQuery<Result<IReadOnlyList<MemberResponse>>>;
public sealed class ListMembersQueryHandler(IRestaurantMembershipRepository repository) : IQueryHandler<ListMembersQuery, Result<IReadOnlyList<MemberResponse>>> { public async Task<Result<IReadOnlyList<MemberResponse>>> Handle(ListMembersQuery query, CancellationToken cancellationToken) => Result.Success(await repository.ListAsync(query.RestaurantId, cancellationToken)); }
public sealed record ListMembershipAuditQuery(RestaurantId RestaurantId) : IQuery<Result<IReadOnlyList<AuditResponse>>>;
public sealed class ListMembershipAuditQueryHandler(IMembershipInvitationRepository repository) : IQueryHandler<ListMembershipAuditQuery, Result<IReadOnlyList<AuditResponse>>> { public async Task<Result<IReadOnlyList<AuditResponse>>> Handle(ListMembershipAuditQuery query, CancellationToken cancellationToken) => Result.Success<IReadOnlyList<AuditResponse>>((await repository.ListAuditAsync(query.RestaurantId, cancellationToken)).Select(x => new AuditResponse(x.Id, x.ActorSubject, x.Action, x.ResourceType, x.ResourceId, x.Changes, x.OccurredAtUtc)).ToArray()); }