// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantMenu.Payments.Infrastructure.Database;

#nullable disable

namespace RestaurantMenu.Payments.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260911080000_InitialPayments")]
    partial class InitialPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantMenu.Payments.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<int>("CommissionRateBasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("commission_rate_basis_points");

                    b.Property<string>("ConnectedAccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("connected_account_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("DiningSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("dining_session_id");

                    b.Property<long>("DiscountAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_amount_minor");

                    b.Property<long>("GrossAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_amount_minor");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<long>("OtherFeeAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("other_fee_amount_minor");

                    b.Property<long>("PlatformFeeAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_fee_amount_minor");

                    b.Property<string>("ProviderPaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_payment_intent_id");

                    b.Property<long>("RefundedAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("refunded_amount_minor");

                    b.Property<long>("RefundedPlatformFeeAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("refunded_platform_fee_amount_minor");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<long>("RestaurantProceedsAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("restaurant_proceeds_amount_minor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("SubtotalAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("subtotal_amount_minor");

                    b.Property<DateTimeOffset?>("SucceededAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("succeeded_at_utc");

                    b.Property<long>("TaxAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("tax_amount_minor");

                    b.Property<long>("TipAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("tip_amount_minor");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_order");

                    b.HasIndex("ProviderPaymentIntentId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_provider_intent")
                        .HasFilter("provider_payment_intent_id IS NOT NULL");

                    b.HasIndex("RestaurantId", "CreatedAtUtc")
                        .HasDatabaseName("ix_payments_restaurant_created");

                    b.ToTable("payments", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payments_commission", "commission_rate_basis_points BETWEEN 1 AND 10000 AND platform_fee_amount_minor >= 0 AND platform_fee_amount_minor <= gross_amount_minor AND restaurant_proceeds_amount_minor = gross_amount_minor - platform_fee_amount_minor");

                            t.HasCheckConstraint("ck_payments_components", "subtotal_amount_minor >= 0 AND discount_amount_minor >= 0 AND discount_amount_minor <= subtotal_amount_minor AND tax_amount_minor >= 0 AND tip_amount_minor >= 0 AND other_fee_amount_minor >= 0");

                            t.HasCheckConstraint("ck_payments_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_payments_gross", "gross_amount_minor = subtotal_amount_minor - discount_amount_minor + tax_amount_minor + tip_amount_minor + other_fee_amount_minor AND gross_amount_minor > 0");

                            t.HasCheckConstraint("ck_payments_refunds", "refunded_amount_minor BETWEEN 0 AND gross_amount_minor AND refunded_platform_fee_amount_minor BETWEEN 0 AND platform_fee_amount_minor");

                            t.HasCheckConstraint("ck_payments_status", "status IN ('Pending', 'Processing', 'Succeeded', 'PartiallyRefunded', 'Refunded', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Payments.Domain.Payments.PaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<long?>("PlatformFeeAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_fee_amount_minor");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_event_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_events_provider_event")
                        .HasFilter("provider_event_id IS NOT NULL");

                    b.HasIndex("PaymentId", "OccurredAtUtc")
                        .HasDatabaseName("ix_payment_events_payment_occurred");

                    b.ToTable("payment_events", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payment_events_amount", "amount_minor IS NULL OR amount_minor >= 0");

                            t.HasCheckConstraint("ck_payment_events_fee", "platform_fee_amount_minor IS NULL OR platform_fee_amount_minor >= 0");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Payments.Domain.Profiles.RestaurantPaymentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CommissionRateBasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("commission_rate_basis_points");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("character(2)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("StripeAccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_account_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_profiles_restaurant");

                    b.HasIndex("StripeAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_profiles_stripe_account");

                    b.ToTable("restaurant_payment_profiles", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payment_profiles_commission", "commission_rate_basis_points BETWEEN 1 AND 10000");

                            t.HasCheckConstraint("ck_payment_profiles_country", "country ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_payment_profiles_currency", "currency ~ '^[A-Z]{3}$'");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Payments.Domain.Payments.PaymentEvent", b =>
                {
                    b.HasOne("RestaurantMenu.Payments.Domain.Payments.Payment", null)
                        .WithMany("Events")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantMenu.Payments.Domain.Payments.Payment", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
