<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RestaurantMenu.Api\RestaurantMenu.Api.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\RestaurantMenu.SharedKernel\RestaurantMenu.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Modules\Restaurants\RestaurantMenu.Restaurants.Domain\RestaurantMenu.Restaurants.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Restaurants\RestaurantMenu.Restaurants.Application\RestaurantMenu.Restaurants.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Restaurants\RestaurantMenu.Restaurants.Infrastructure\RestaurantMenu.Restaurants.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Restaurants\RestaurantMenu.Restaurants.Presentation\RestaurantMenu.Restaurants.Presentation.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\RestaurantMenu.Catalog.Domain\RestaurantMenu.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\RestaurantMenu.Application.Abstractions\RestaurantMenu.Application.Abstractions.csproj" />
  </ItemGroup>

</Project>
