// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantMenu.Ordering.Infrastructure.Database;

#nullable disable

namespace RestaurantMenu.Ordering.Infrastructure.Database.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20260911093635_AddOrderTaxSnapshots")]
    partial class AddOrderTaxSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ordering")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantMenu.Ordering.Domain.DiningSessions.DiningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DiningTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("dining_table_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_dining_sessions_expires_at_utc");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_dining_sessions_token_hash");

                    b.HasIndex("RestaurantId", "BranchId", "DiningTableId")
                        .HasDatabaseName("ix_dining_sessions_scope");

                    b.ToTable("dining_sessions", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_dining_sessions_expiry", "expires_at_utc > created_at_utc");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Ordering.Domain.Orders.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash")
                        .IsFixedLength();

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_idempotency_records_expires_at_utc");

                    b.HasIndex("ResourceId");

                    b.HasIndex("Scope", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_records_scope_key");

                    b.ToTable("idempotency_records", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_records_expiry", "expires_at_utc > created_at_utc");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Ordering.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("customer_note");

                    b.Property<Guid>("DiningSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("dining_session_id");

                    b.Property<Guid>("DiningTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("dining_table_id");

                    b.Property<string>("PublicNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("public_number");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal_amount");

                    b.Property<string>("TableDisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("table_display_name");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PublicNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_public_number");

                    b.HasIndex("DiningSessionId", "CreatedAtUtc")
                        .HasDatabaseName("ix_orders_dining_session");

                    b.HasIndex("RestaurantId", "BranchId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_orders_branch_queue");

                    b.ToTable("orders", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_orders_amounts", "subtotal_amount >= 0 AND tax_amount >= 0 AND total_amount = subtotal_amount + tax_amount");

                            t.HasCheckConstraint("ck_orders_currency", "char_length(currency) = 3");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('Placed', 'Accepted', 'Preparing', 'Ready', 'Served', 'Completed', 'Rejected', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Ordering.Domain.Orders.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("item_name");

                    b.Property<decimal>("LineTotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total_amount");

                    b.Property<Guid?>("MenuItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_item_id");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxBehavior")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tax_behavior");

                    b.Property<int>("TaxRateBasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("tax_rate_basis_points");

                    b.Property<decimal>("UnitPriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price_amount");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<string>("VariantName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("variant_name");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_lines_order_id");

                    b.ToTable("order_lines", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_order_lines_amounts", "unit_price_amount >= 0 AND net_amount >= 0 AND tax_amount >= 0 AND line_total_amount = net_amount + tax_amount");

                            t.HasCheckConstraint("ck_order_lines_currency", "char_length(currency) = 3");

                            t.HasCheckConstraint("ck_order_lines_quantity", "quantity BETWEEN 1 AND 99");

                            t.HasCheckConstraint("ck_order_lines_tax_behavior", "tax_behavior IN ('Inclusive', 'Exclusive')");

                            t.HasCheckConstraint("ck_order_lines_tax_rate", "tax_rate_basis_points BETWEEN 0 AND 10000");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Ordering.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangedBySubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("changed_by_subject");

                    b.Property<string>("ChangedByType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("changed_by_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_order_status_history_order_created");

                    b.ToTable("order_status_history", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_order_status_history_actor", "changed_by_type IN ('Guest', 'Staff', 'System')");

                            t.HasCheckConstraint("ck_order_status_history_from", "from_status IS NULL OR from_status IN ('Placed', 'Accepted', 'Preparing', 'Ready', 'Served', 'Completed', 'Rejected', 'Cancelled')");

                            t.HasCheckConstraint("ck_order_status_history_to", "to_status IN ('Placed', 'Accepted', 'Preparing', 'Ready', 'Served', 'Completed', 'Rejected', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Ordering.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at_utc");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.HasKey("MessageId", "Consumer");

                    b.HasIndex("DeadLetteredAtUtc")
                        .HasDatabaseName("ix_inbox_dead_lettered")
                        .HasFilter("dead_lettered_at_utc IS NOT NULL");

                    b.ToTable("inbox_messages", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_inbox_attempt_count", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Ordering.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at_utc");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("trace_state");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId", "AggregateVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_aggregate_version");

                    b.HasIndex("NextAttemptAtUtc", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("processed_at_utc IS NULL AND dead_lettered_at_utc IS NULL");

                    b.ToTable("outbox_messages", "ordering", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_aggregate_version", "aggregate_version > 0");

                            t.HasCheckConstraint("ck_outbox_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_outbox_event_version", "event_version > 0");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Ordering.Domain.Orders.IdempotencyRecord", b =>
                {
                    b.HasOne("RestaurantMenu.Ordering.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantMenu.Ordering.Domain.Orders.OrderLine", b =>
                {
                    b.HasOne("RestaurantMenu.Ordering.Domain.Orders.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantMenu.Ordering.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.HasOne("RestaurantMenu.Ordering.Domain.Orders.Order", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantMenu.Ordering.Domain.Orders.Order", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
