<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RestaurantMenu.Restaurants.Application\RestaurantMenu.Restaurants.Application.csproj" />
    <ProjectReference Include="..\RestaurantMenu.Restaurants.Domain\RestaurantMenu.Restaurants.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\RestaurantMenu.Application.Abstractions\RestaurantMenu.Application.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
