// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantMenu.Catalog.Infrastructure.Database;

#nullable disable

namespace RestaurantMenu.Catalog.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260909143947_AddCatalogMediaAssociations")]
    partial class AddCatalogMediaAssociations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantMenu.Catalog.Domain.Categories.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid?>("ImageMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_media_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RestaurantId", "DisplayOrder")
                        .HasDatabaseName("ix_menu_categories_restaurant_id_display_order");

                    b.ToTable("menu_categories", "catalog");
                });

            modelBuilder.Entity("RestaurantMenu.Catalog.Domain.Items.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllergenNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("allergen_notes");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer")
                        .HasColumnName("calories");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<short?>("PreparationTimeMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("preparation_time_minutes");

                    b.Property<string>("Recipe")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("recipe");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_menu_items_tags_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("RestaurantId", "CategoryId", "DisplayOrder")
                        .HasDatabaseName("ix_menu_items_restaurant_category_display_order");

                    b.ToTable("menu_items", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_menu_items_calories_non_negative", "calories IS NULL OR calories >= 0");

                            t.HasCheckConstraint("ck_menu_items_preparation_time_minutes_range", "preparation_time_minutes IS NULL OR (preparation_time_minutes >= 1 AND preparation_time_minutes <= 1440)");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Catalog.Domain.Items.MenuItemMedia", b =>
                {
                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_item_id");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alt_text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("MenuItemId", "MediaAssetId");

                    b.HasIndex("RestaurantId", "MenuItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_menu_item_media_primary")
                        .HasFilter("is_primary");

                    b.HasIndex("RestaurantId", "MenuItemId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_menu_item_media_order");

                    b.ToTable("menu_item_media", "catalog");
                });

            modelBuilder.Entity("RestaurantMenu.Catalog.Domain.Publications.BranchCategoryPublication", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("DisplayOrderOverride")
                        .HasColumnType("integer")
                        .HasColumnName("display_order_override");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("BranchId", "CategoryId");

                    b.HasIndex("RestaurantId", "CategoryId")
                        .HasDatabaseName("ix_branch_category_publications_restaurant_id_category_id");

                    b.HasIndex("RestaurantId", "BranchId", "IsPublished", "DisplayOrderOverride")
                        .HasDatabaseName("ix_branch_category_publications_public_menu");

                    b.ToTable("branch_category_publications", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_branch_category_publications_display_order_override", "display_order_override IS NULL OR display_order_override >= 0");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Catalog.Domain.Variants.MenuItemVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_menu_item_variants_one_default")
                        .HasFilter("is_default = TRUE AND is_deleted = FALSE");

                    b.HasIndex("MenuItemId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_menu_item_variants_active_name")
                        .HasFilter("is_deleted = FALSE");

                    b.HasIndex("RestaurantId", "MenuItemId", "DisplayOrder")
                        .HasDatabaseName("ix_menu_item_variants_restaurant_item_display_order");

                    b.ToTable("menu_item_variants", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_menu_item_variants_currency_format", "price_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_menu_item_variants_display_order_non_negative", "display_order >= 0");

                            t.HasCheckConstraint("ck_menu_item_variants_price_non_negative", "price_amount >= 0");
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Catalog.Domain.Categories.MenuCategory", b =>
                {
                    b.HasOne("RestaurantMenu.Catalog.Domain.Categories.MenuCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RestaurantMenu.Catalog.Domain.Items.MenuItem", b =>
                {
                    b.HasOne("RestaurantMenu.Catalog.Domain.Categories.MenuCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantMenu.Catalog.Domain.Items.MenuItemMedia", b =>
                {
                    b.HasOne("RestaurantMenu.Catalog.Domain.Items.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId", "MenuItemId")
                        .HasPrincipalKey("RestaurantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantMenu.Catalog.Domain.Publications.BranchCategoryPublication", b =>
                {
                    b.HasOne("RestaurantMenu.Catalog.Domain.Categories.MenuCategory", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId", "CategoryId")
                        .HasPrincipalKey("RestaurantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantMenu.Catalog.Domain.Variants.MenuItemVariant", b =>
                {
                    b.HasOne("RestaurantMenu.Catalog.Domain.Items.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId", "MenuItemId")
                        .HasPrincipalKey("RestaurantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("RestaurantMenu.Catalog.Domain.Items.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("MenuItemVariantId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("character(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("MenuItemVariantId");

                            b1.ToTable("menu_item_variants", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemVariantId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
