<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup><Using Include="Xunit" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\Notifications\RestaurantMenu.Notifications.Application\RestaurantMenu.Notifications.Application.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\Notifications\RestaurantMenu.Notifications.Infrastructure\RestaurantMenu.Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\Ordering\RestaurantMenu.Ordering.Infrastructure\RestaurantMenu.Ordering.Infrastructure.csproj" />
  </ItemGroup>
</Project>
